// <auto-generated />
using System;
using Assignment1Group26.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment1Group26.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230226075345_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assignment1Group26.Models.AssetCondition", b =>
                {
                    b.Property<int>("AssetConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetConditionId"), 1L, 1);

                    b.Property<string>("AssetConditionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetConditionId");

                    b.ToTable("assetConditions");

                    b.HasData(
                        new
                        {
                            AssetConditionId = 1,
                            AssetConditionStatus = "New"
                        },
                        new
                        {
                            AssetConditionId = 2,
                            AssetConditionStatus = "Lightly Used"
                        },
                        new
                        {
                            AssetConditionId = 3,
                            AssetConditionStatus = "Used"
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"), 1L, 1);

                    b.Property<int>("AssetConditionId")
                        .HasColumnType("int");

                    b.Property<double?>("BidCost")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("BidDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BidId");

                    b.HasIndex("AssetConditionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientId");

                    b.ToTable("bids");

                    b.HasData(
                        new
                        {
                            BidId = 1,
                            AssetConditionId = 1,
                            BidCost = 59.990000000000002,
                            BidDescription = "High heel slingback shoes. Tied closure. Pointed toe.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3710),
                            BidName = "LACE UP TIED HIGH HEELED SHOES",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3708),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/shoes.jpg"
                        },
                        new
                        {
                            BidId = 2,
                            AssetConditionId = 2,
                            BidCost = 45.899999999999999,
                            BidDescription = "Mini city bag. Handle and removable, adjustable crossbody strap. Magnetic closure.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3720),
                            BidName = "MINI CITY BAG",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3718),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/pinkBag.jpg"
                        },
                        new
                        {
                            BidId = 3,
                            AssetConditionId = 1,
                            BidCost = 69.989999999999995,
                            BidDescription = "Mid-rise jeans with front pockets .",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3725),
                            BidName = "WOMEN'S BELT LOOP CARGO TRF JEANS",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3724),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/jeans.jpg"
                        },
                        new
                        {
                            BidId = 4,
                            AssetConditionId = 1,
                            BidCost = 39.990000000000002,
                            BidDescription = "Openwork knit top with round neck and short sleeves.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3730),
                            BidName = "RUFFLED KNIT TOP",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3728),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/knitShirt.jpg"
                        },
                        new
                        {
                            BidId = 5,
                            AssetConditionId = 3,
                            BidCost = 29.989999999999998,
                            BidDescription = "Long sleeves. Rib trim.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3734),
                            BidName = "ZIP COLLAR SWEATSHIRT",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3733),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/menBlueHoddie.jpg"
                        },
                        new
                        {
                            BidId = 6,
                            AssetConditionId = 1,
                            BidCost = 129.99000000000001,
                            BidDescription = "Coat made of wool blend fabric.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3739),
                            BidName = "WOOL BLEND COAT",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3738),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/coat.jpg"
                        },
                        new
                        {
                            BidId = 7,
                            AssetConditionId = 2,
                            BidCost = 129.99000000000001,
                            BidDescription = "Sneakers.Slightly chunky soles.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3744),
                            BidName = "RUNNING SHOES",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3743),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/runningShoes.jpg"
                        },
                        new
                        {
                            BidId = 8,
                            AssetConditionId = 3,
                            BidCost = 19.989999999999998,
                            BidDescription = "Cotton sweater vest. Sleeveless. V-neckline. Rib trim.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3749),
                            BidName = "TEXTURED KNIT VEST",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3747),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/vest.jpg"
                        },
                        new
                        {
                            BidId = 9,
                            AssetConditionId = 1,
                            BidCost = 29.989999999999998,
                            BidDescription = "Girl short sleeves dress with elastic cuffs.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3754),
                            BidName = "ASSYMETRIC POPLIN DRESS",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3752),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/girlDress.jpg"
                        },
                        new
                        {
                            BidId = 10,
                            AssetConditionId = 3,
                            BidCost = 19.989999999999998,
                            BidDescription = "Girl short sleeves dress with elastic cuffs.",
                            BidEndDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3758),
                            BidName = "ASSYMETRIC POPLIN DRESS",
                            BidStartDate = new DateTime(2023, 2, 26, 2, 53, 45, 527, DateTimeKind.Local).AddTicks(3757),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/girlDress.jpg"
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Clothes"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cars"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Electronics"
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("ClienFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPassword")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClientUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfimed")
                        .HasColumnType("bit");

                    b.Property<string>("VerficationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("keepLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("ClientId");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ClienFirstName = "John",
                            ClienLastName = "Smith",
                            ClientPassword = "password",
                            ClientUserName = "john.smith@gmail.com",
                            EmailConfimed = false,
                            keepLoggedIn = false
                        },
                        new
                        {
                            ClientId = 2,
                            ClienFirstName = "vedoor",
                            ClienLastName = "Barakat",
                            ClientPassword = "password",
                            ClientUserName = "Vendor.Barakat@gmail.com",
                            EmailConfimed = false,
                            keepLoggedIn = false
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Bid", b =>
                {
                    b.HasOne("Assignment1Group26.Models.AssetCondition", "AssetCondition")
                        .WithMany()
                        .HasForeignKey("AssetConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment1Group26.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment1Group26.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetCondition");

                    b.Navigation("Category");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
