// <auto-generated />
using System;
using Assignment1Group26.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment1Group26.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230301160206_mssql_migration_270")]
    partial class mssql_migration_270
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assignment1Group26.Models.AssetCondition", b =>
                {
                    b.Property<int>("AssetConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetConditionId"), 1L, 1);

                    b.Property<string>("AssetConditionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetConditionId");

                    b.ToTable("assetConditions");

                    b.HasData(
                        new
                        {
                            AssetConditionId = 1,
                            AssetConditionStatus = "New"
                        },
                        new
                        {
                            AssetConditionId = 2,
                            AssetConditionStatus = "Lightly Used"
                        },
                        new
                        {
                            AssetConditionId = 3,
                            AssetConditionStatus = "Used"
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"), 1L, 1);

                    b.Property<int>("AssetConditionId")
                        .HasColumnType("int");

                    b.Property<double?>("BidCost")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("BidDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BidStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BidId");

                    b.HasIndex("AssetConditionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientId");

                    b.ToTable("bids");

                    b.HasData(
                        new
                        {
                            BidId = 1,
                            AssetConditionId = 1,
                            BidCost = 59.990000000000002,
                            BidDescription = "High heel slingback shoes. Tied closure. Pointed toe.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7067),
                            BidName = "LACE UP TIED HIGH HEELED SHOES",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7065),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/shoes.jpg"
                        },
                        new
                        {
                            BidId = 2,
                            AssetConditionId = 2,
                            BidCost = 45.899999999999999,
                            BidDescription = "Mini city bag. Handle and removable, adjustable crossbody strap. Magnetic closure.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7075),
                            BidName = "MINI CITY BAG",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7073),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/pinkBag.jpg"
                        },
                        new
                        {
                            BidId = 3,
                            AssetConditionId = 1,
                            BidCost = 69.989999999999995,
                            BidDescription = "Mid-rise jeans with front pockets .",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7079),
                            BidName = "WOMEN'S BELT LOOP CARGO TRF JEANS",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7078),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/jeans.jpg"
                        },
                        new
                        {
                            BidId = 4,
                            AssetConditionId = 1,
                            BidCost = 39.990000000000002,
                            BidDescription = "Openwork knit top with round neck and short sleeves.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7083),
                            BidName = "RUFFLED KNIT TOP",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7082),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/knitShirt.jpg"
                        },
                        new
                        {
                            BidId = 5,
                            AssetConditionId = 3,
                            BidCost = 29.989999999999998,
                            BidDescription = "Long sleeves. Rib trim.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7087),
                            BidName = "ZIP COLLAR SWEATSHIRT",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7086),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/menBlueHoddie.jpg"
                        },
                        new
                        {
                            BidId = 6,
                            AssetConditionId = 1,
                            BidCost = 129.99000000000001,
                            BidDescription = "Coat made of wool blend fabric.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7091),
                            BidName = "WOOL BLEND COAT",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7090),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/coat.jpg"
                        },
                        new
                        {
                            BidId = 7,
                            AssetConditionId = 2,
                            BidCost = 129.99000000000001,
                            BidDescription = "Sneakers.Slightly chunky soles.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7094),
                            BidName = "RUNNING SHOES",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7093),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/runningShoes.jpg"
                        },
                        new
                        {
                            BidId = 8,
                            AssetConditionId = 3,
                            BidCost = 19.989999999999998,
                            BidDescription = "Cotton sweater vest. Sleeveless. V-neckline. Rib trim.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7098),
                            BidName = "TEXTURED KNIT VEST",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7097),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/vest.jpg"
                        },
                        new
                        {
                            BidId = 9,
                            AssetConditionId = 1,
                            BidCost = 29.989999999999998,
                            BidDescription = "Girl short sleeves dress with elastic cuffs.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7102),
                            BidName = "ASSYMETRIC POPLIN DRESS",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7101),
                            CategoryId = 1,
                            ClientId = 1,
                            ImagePath = "~/Images/girlDress.jpg"
                        },
                        new
                        {
                            BidId = 10,
                            AssetConditionId = 3,
                            BidCost = 649.99000000000001,
                            BidDescription = "onsumer Notebook 15.6 FHD AMD Ryzen 5 5625U AMD Radeon Graphics 12GB 512GB SSD Windows 11 Home ",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7105),
                            BidName = "LENOVO IdeaPad 3",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7104),
                            CategoryId = 3,
                            ClientId = 1,
                            ImagePath = "~/Images/lenovoIdeaPad3.jpg"
                        },
                        new
                        {
                            BidId = 11,
                            AssetConditionId = 1,
                            BidCost = 1200.99,
                            BidDescription = "16.1 QHD, Intel Core i7-11800H, NVIDIA GeForce RTX 3070, 16GB DDR4, 1TB SSD.",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7109),
                            BidName = "HP OMEN 16-b0020ca Gaming Notebook",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7108),
                            CategoryId = 3,
                            ClientId = 1,
                            ImagePath = "~/Images/omen.jpg"
                        },
                        new
                        {
                            BidId = 12,
                            AssetConditionId = 3,
                            BidCost = 899.99000000000001,
                            BidDescription = "256GB Gold",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7112),
                            BidName = "IPHONE 14 PRO MAX",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7111),
                            CategoryId = 3,
                            ClientId = 1,
                            ImagePath = "~/Images/iphone14.jpg"
                        },
                        new
                        {
                            BidId = 13,
                            AssetConditionId = 1,
                            BidCost = 25250.0,
                            BidDescription = "2018 MAZDA 3",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7116),
                            BidName = "MAZDA 3",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7115),
                            CategoryId = 2,
                            ClientId = 2,
                            ImagePath = "~/Images/mazda32018.jpg"
                        },
                        new
                        {
                            BidId = 14,
                            AssetConditionId = 1,
                            BidCost = 50150.0,
                            BidDescription = "VW 310 Rampaging German Horse Power",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7119),
                            BidName = "Golf R",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7118),
                            CategoryId = 2,
                            ClientId = 1,
                            ImagePath = "~/Images/golfR.jpg"
                        },
                        new
                        {
                            BidId = 15,
                            AssetConditionId = 1,
                            BidCost = 70120.300000000003,
                            BidDescription = "2023 chevy pick up Truck",
                            BidEndDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7123),
                            BidName = "Chevy Silverado",
                            BidStartDate = new DateTime(2023, 3, 1, 11, 2, 6, 304, DateTimeKind.Local).AddTicks(7122),
                            CategoryId = 2,
                            ClientId = 2,
                            ImagePath = "~/Images/chevySilverado.jpg"
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Clothes"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Cars"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Electronics"
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("ClienFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPassword")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClientUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("VerficationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("keepLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("ClientId");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ClienFirstName = "John",
                            ClienLastName = "Smith",
                            ClientPassword = "password",
                            ClientUserName = "john.smith@gmail.com",
                            EmailConfirmed = true,
                            keepLoggedIn = false
                        },
                        new
                        {
                            ClientId = 2,
                            ClienFirstName = "vedoor",
                            ClienLastName = "Barakat",
                            ClientPassword = "password",
                            ClientUserName = "Vendor.Barakat@gmail.com",
                            EmailConfirmed = true,
                            keepLoggedIn = false
                        });
                });

            modelBuilder.Entity("Assignment1Group26.Models.Bid", b =>
                {
                    b.HasOne("Assignment1Group26.Models.AssetCondition", "AssetCondition")
                        .WithMany()
                        .HasForeignKey("AssetConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment1Group26.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment1Group26.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetCondition");

                    b.Navigation("Category");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
